# Generated by Django 4.1.7 on 2023-05-12 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=25, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="mainCategory",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=25, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Seller",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=70)),
                ("username", models.CharField(max_length=50, unique=True)),
                ("phone", models.IntegerField()),
                ("pin", models.IntegerField(blank=True, null=True)),
                (
                    "city",
                    models.CharField(blank=True, default="", max_length=50, null=True),
                ),
                (
                    "state",
                    models.CharField(blank=True, default="", max_length=50, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="subCategory",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=25, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("baseprice", models.IntegerField()),
                ("discount", models.IntegerField(default=0)),
                ("finalPrice", models.IntegerField()),
                ("color", models.CharField(max_length=20)),
                ("size", models.CharField(max_length=10)),
                ("desc", models.TextField()),
                ("stock", models.BooleanField(default=True)),
                ("time", models.DateField(auto_now=True)),
                ("pic1", models.ImageField(upload_to="productimg/")),
                ("pic2", models.ImageField(upload_to="productimg/")),
                ("pic3", models.ImageField(upload_to="productimg/")),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="mainApp.brand"
                    ),
                ),
                (
                    "maincat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mainApp.maincategory",
                    ),
                ),
                (
                    "subcat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mainApp.subcategory",
                    ),
                ),
            ],
        ),
    ]
